# Generated by Django 5.1 on 2024-09-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="name",
            field=models.CharField(default="Default Room Name", max_length=255),
            preserve_default=False,
        ),
    ]
