# Generated by Django 5.1 on 2024-09-09 04:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_room_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="code",
            field=models.CharField(
                default=api.models.generate_unique_code, max_length=8, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="host",
            field=models.CharField(max_length=255),
        ),
    ]
